package com.example.panicattackhdt.storage

import android.content.Context
import android.os.Build
import androidx.annotation.RequiresApi
import com.example.panicattackhdt.model.RecordData
import com.example.panicattackhdt.model.RecordDataJson
import com.example.panicattackhdt.model.Symptom
import com.example.panicattackhdt.model.toJsonData
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json
import java.io.File
import java.time.LocalDateTime

// AI generated code, generated by ChatGPT, 03,25,2026
@RequiresApi(Build.VERSION_CODES.O)
fun loadRecords(context: Context): List<RecordData> {
    val file = File(context.filesDir, "HistoryData.json")

    val json = file.readText()
        .replace("[", "")
        .replace("]", "")
        .split("},")
        .map { it.trim() + if (!it.trim().endsWith("}")) "}" else "" }

    val records = mutableListOf<RecordData>()

    for (item in json) {
        val startTime = """"startTime":\s*"([^"]+)"""".toRegex().find(item)?.groups?.get(1)?.value ?: continue
        val endTime = """"endTime":\s*"([^"]+)"""".toRegex().find(item)?.groups?.get(1)?.value ?: continue
        val severity = """"severity":\s*(\d+)""".toRegex().find(item)?.groups?.get(1)?.value?.toInt() ?: 0
        val peak = """"peak":\s*(\d+)""".toRegex().find(item)?.groups?.get(1)?.value?.toInt() ?: 0
        val trigger = """"trigger":\s*"([^"]+)"""".toRegex().find(item)?.groups?.get(1)?.value ?: ""
        val location = """"location":\s*"([^"]+)"""".toRegex().find(item)?.groups?.get(1)?.value ?: ""
        val notes = """"notes":\s*"([^"]+)"""".toRegex().find(item)?.groups?.get(1)?.value ?: ""
        val symptomsStr = """"symptoms":\s*\[([^\]]*)]""".toRegex().find(item)?.groups?.get(1)?.value ?: ""
        val symptoms = symptomsStr.split(",").mapNotNull { s ->
            Symptom.values().find { it.name == s.trim().replace("\"", "") }
        }

        records.add(
            RecordData(
                startTime = LocalDateTime.parse(startTime),
                endTime = LocalDateTime.parse(endTime),
                severity = severity,
                symptoms = symptoms,
                trigger = trigger,
                location = location,
                notes = notes,
                peak = peak
            )
        )
    }
    return records
}

fun saveRecords(context: Context, records: MutableList<RecordData>) {
    val file = File(context.filesDir, "HistoryData.json")
    val jsonString = "[${records.joinToString(",") { r ->
        val symptomsStr = r.symptoms.joinToString(",") { "\"${it.name}\"" }
        """
        {
          "startTime": "${r.startTime}",
          "endTime": "${r.endTime}",
          "severity": ${r.severity},
          "symptoms": [$symptomsStr],
          "trigger": "${r.trigger}",
          "location": "${r.location}",
          "notes": "${r.notes}",
          "peak": ${r.peak}
        }
        """.trimIndent()
    }}]"
    file.writeText(jsonString)
}

fun copyAssetsToInternal(context: Context, fileName: String) {
    val file = File(context.filesDir, fileName)
    if (!file.exists()) {
        context.assets.open(fileName).use { input ->
            file.outputStream().use { output ->
                input.copyTo(output)
            }
        }
    }
}

object DataStorage {
    private val records = mutableListOf<RecordData>()

    @RequiresApi(Build.VERSION_CODES.O)
    fun init(context: Context) {
        records.clear()
        records.addAll(loadRecords(context))
    }
    fun getAll(): List<RecordData> = records.toList()
    fun add(context: Context, record: RecordData) {
        records.add(record)
        saveRecords(context, records)
    }
}